"""add property_images and property features

Revision ID: c67ff5f7d750
Revises: 9d7c159024d0
Create Date: 2026-02-19 09:41:10.797942

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c67ff5f7d750'
down_revision = '9d7c159024d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.add_column('properties', sa.Column('parking_spaces', sa.Integer(), nullable=False))
    op.add_column('properties', sa.Column('has_pool', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('has_garden', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('furnished', sa.Boolean(), nullable=False))
    op.drop_index('idx_properties_city', table_name='properties')
    op.drop_index('idx_properties_price', table_name='properties')
    op.drop_index('idx_properties_status', table_name='properties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_properties_status', 'properties', ['status'], unique=False)
    op.create_index('idx_properties_price', 'properties', ['price'], unique=False)
    op.create_index('idx_properties_city', 'properties', ['city'], unique=False)
    op.drop_column('properties', 'furnished')
    op.drop_column('properties', 'has_garden')
    op.drop_column('properties', 'has_pool')
    op.drop_column('properties', 'parking_spaces')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    # ### end Alembic commands ###
